### ISSUE TITLE
install script is installing undocumented software

### ISSUE THREAD

**Issue by PinkFlufflyLlama** [ArtistXoder/MinecraftServer#2]
Your install script is installing antivirus software that is not mentioned in the readme. While there is no malicious intent and you may expect it to be installed for your setup but another user may not realize or expect that you are going to install the program.

in a similar vein, installing and enabling ufw, while a good idea my not be expected and could break other services running on the user's pi

Also what is port 22 doing being opened?

**Comment by ArtistXoder** [comment]
Well sorry I just got you comment. And the reason port 22 is open is because I sh its for performing. Also if you would like to help you can. Um I forgot to added in the Readme the software that is being installed I was trying to make it easier for new people to install software and get minecraft sever setup. I am also really new to github.
